#!/bin/bash

shark_dirs=$(ls -d shark*)
dir_list=("$shark_dirs")

# NOTE: the order matters but this is the right one
for i in ${dir_list[@]}; do
	echo building $i;
	cd $i;
	cat build;
	. build;
	cd ..;
done
