#!/bin/bash

mesos_dirs=$(ls -d mesos* spark-shell shark-shell)
dir_list=("$mesos_dirs")

# NOTE: the order matters but this is the right one
for i in ${dir_list[@]}; do
	echo building $i;
	cd $i;
	cat build;
	. build;
	cd ..;
done
