#!/bin/bash

# run this as:
#   sudo docker run -i -t -d shark-master:$SHARK_VERSION

source /root/shark_files/configure_shark.sh

IP=$(ip -o -4 addr list eth0 | perl -n -e 'if (m{inet\s([\d\.]+)\/\d+\s}xms) { print $1 }')
echo "MASTER_IP=$IP"
prepare_shark $IP
sudo -u hdfs hadoop namenode -format
service hadoop-namenode start
/usr/sbin/sshd
sleep 5
cp /root/shark_master_files/run_shark_master.sh /
chmod a+rx /run_shark_master.sh
#nohup sudo -u hdfs /run_shark_master.sh $IP &
sudo -u hdfs /run_shark_master.sh $IP
#sleep 20
#cd /opt/metastore && sudo -u hdfs /opt/shark-$SHARK_VERSION/bin/shark
