#!/bin/bash

# run this as:
#    sudo docker run -d shark-worker:${SHARK_VERSION} ${MASTER_IP} spark://${MASTER_IP}:7077

source /root/shark_files/configure_shark.sh

prepare_shark $1
service hadoop-datanode start
sleep 5
cp /root/shark_worker_files/run_shark_worker.sh /
chmod a+rx /run_shark_worker.sh
sudo -u hdfs /run_shark_worker.sh $2
