#!/bin/bash

# determines which Shark image is chosen
SHARK_VERSION=0.7.0

# set this value to the number of workers you want
NUM_WORKERS=2

if [[ "$USER" != "root" ]]; then
   echo "please run as: sudo $0"
   exit 1
fi

start_shell=0
VOLUME_MAP=""

while getopts ":cv:h" opt; do
    case $opt in
    h)
        echo "usage: $0 [-v data_directory] [-c]"
        exit 0
      ;;
    c)
        start_shell=1
      ;;
    v)
        VOLUME_MAP=$OPTARG
      ;;
  esac
done

if [ ! "$VOLUME_MAP" == "" ]; then
    echo "data volume chosen: $VOLUME_MAP"
    VOLUME_MAP="-v $VOLUME_MAP:/data"
fi

source ../../dnsmasq-precise/deploy/start_nameserver.sh
source start_shark_cluster.sh

echo "*** Starting Shark $SHARK_VERSION + Spark ***"
start_nameserver
sleep 10
start_shark_master
sleep 40
start_shark_workers
sleep 3
print_cluster_info

# parameter -c causes us to directly fall into a Shark shell
if [[ "$start_shell" -eq 1 ]];
then
    sudo docker run -i -t shark-shell:$SHARK_VERSION $MASTER_IP
fi
