#!/bin/sh

SHARK_VERSION=0.7.0

MASTER=$(sudo docker run -i -t -d shark-master:$SHARK_VERSION)
echo "started master container:   $MASTER"
sleep 60
MASTER_IP=$(sudo docker logs $MASTER 2>&1 | egrep '^MASTER_IP=' | awk -F= '{print $2}' | tr -d -c "[:digit:] .")
echo "MASTER_IP: $MASTER_IP"
WORKER=$(sudo docker run -d shark-worker:${SHARK_VERSION} ${MASTER_IP} spark://${MASTER_IP}:7077)
echo "started worker container    $WORKER"
echo ""
echo "connect to shark via:       sudo docker run -i -t shark-shell:$SHARK_VERSION $MASTER_IP"
echo ""
echo "visit Spark WebUI at:       http://$MASTER_IP:8080/"
echo "visit Hadoop Namenode at:   http://$MASTER_IP:50070"
echo ""
echo "kill cluster via:           sudo docker kill $MASTER"
