#!/bin/bash

# determines which Spark image is chosen
SPARK_VERSION=0.9.0

# set this value to the number of workers you want
NUM_WORKERS=2

if [[ "$USER" != "root" ]]; then
   echo "please run as: sudo $0"
   exit 1
fi

source ../../dnsmasq-precise/deploy/start_nameserver.sh
source ../../spark/deploy/start_spark_cluster.sh

echo "*** Starting Spark $SPARK_VERSION ***"
start_nameserver
sleep 5
start_spark_master
sleep 40
start_spark_workers
sleep 3
print_cluster_info

# parameter -c causes us to directly fall into a Spark shell
if [[ "$#" -eq 1 ]] && [[ "$1" == "-c" ]];
then
    sudo docker run -i -t -dns $NAMESERVER_IP spark-shell:$SPARK_VERSION $MASTER_IP
fi
